[package]
name = "rusty-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
capstone = "0.13.0"
libc = "0.2.174"
log = "0.4.27"
mockall = "0.13.1"
nix = { version = "0.30", features = ["process", "ptrace", "signal"] }
